# Generated by Django 2.0.6 on 2018-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strl_app', '0002_auto_20180706_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='cur_json',
            new_name='init_info',
        ),
        migrations.RemoveField(
            model_name='world',
            name='init_json',
        ),
    ]
